### ISSUE TITLE
Support for installing public packages using pip or conda?

### ISSUE THREAD

**Issue by ShangChien** [wasmerio/edge-py-http-server#1]

**Comment by theduke** [comment]
You can create a virtual env and include it in the package through the `[fs]`  section, and then extend the package search path, eg with `sys.path.append`.

We'll publish a tutorial for this soon.

**Comment by theduke** [comment]
Note though that at the moment you can only use pure Python dependencies without any native code.

**Comment by ShangChien** [comment]
Thank you for your replay. 
The main reason to write python code is the ecosystem library or the  ML frameworks.

**Comment by ShangChien** [comment]
by the way, does it backend on [pyodide](https://github.com/pyodide/pyodide) ?
